#CMAKE_ANDROID_ARCH_ABI 外部选择想要的架构

set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 21)
set(CMAKE_ANDROID_ARCH_ABI arm64-v8a)
set(CMAKE_ANDROID_STL_TYPE c++_static)
set(CMAKE_ANDROID_NDK ${USER_PATH}/Library/Android/sdk/ndk/23.1.7779620/)